
#include "stdafx.h"
#include "NoahApp.h"
#include "SubDlg.h"

int CArcViewDlg::st_nLife;
static const int ARCVIEW_SPLITTER_WIDTH = 3;

// Binary-search a folder path in m_folderPaths using m_folderSorted. Defined
// later in this file; forward-declared here for use inside CArcViewDlg::onInit.
static unsigned int folder_bisect( const StrArray& paths, const kiArray<unsigned int>& sorted,
	const char* buf, bool* found );

// Extract the last path component (without trailing separator) of a folder
// path that ends in '/' or '\' (e.g. "foo/bar/" -> "bar").
static void extract_folder_leaf( const char* path, char* out )
{
	int pathLen = ::lstrlen( path );
	int end = pathLen;
	if( end > 0 && (path[end-1] == '/' || path[end-1] == '\\') ) end--;
	int start = 0;
	for( int k = end - 1; k >= 0; k-- )
		if( path[k] == '/' || path[k] == '\\' ) { start = k + 1; break; }
	int n = end - start;
	for( int i = 0; i < n; i++ ) out[i] = path[start + i];
	out[n] = '\0';
}

// Subclass proc for the ListView header: gray background + 1px separator line
static LRESULT CALLBACK HeaderSubclassProc(HWND hwnd, UINT msg, WPARAM wp, LPARAM lp)
{
	WNDPROC oldProc = (WNDPROC)::GetProp(hwnd, "NHdrProc");
	if( msg == WM_ERASEBKGND )
	{
		HDC hdc = (HDC)wp;
		RECT rc; ::GetClientRect(hwnd, &rc);
		HBRUSH br = ::CreateSolidBrush(::GetSysColor(COLOR_BTNFACE));
		::FillRect(hdc, &rc, br);
		::DeleteObject(br);
		return TRUE;
	}
	LRESULT r = ::CallWindowProc(oldProc, hwnd, msg, wp, lp);
	if( msg == WM_PAINT )
	{
		RECT rc; ::GetClientRect(hwnd, &rc);
		HDC hdc = ::GetDC(hwnd);
		HPEN pen = ::CreatePen(PS_SOLID, 1, ::GetSysColor(COLOR_BTNSHADOW));
		HPEN oldPen = (HPEN)::SelectObject(hdc, pen);
		::MoveToEx(hdc, 0, rc.bottom - 1, NULL);
		::LineTo(hdc, rc.right, rc.bottom - 1);
		::SelectObject(hdc, oldPen);
		::DeleteObject(pen);
		::ReleaseDC(hwnd, hdc);
	}
	return r;
}

BOOL CArcViewDlg::onInit()
{
	kiStr str;
	kiPath path;
	SHFILEINFO sfi,lfi;
	HIMAGELIST hImS,hImL;
	kiListView ctrl( this, IDC_FILELIST );

	//-- Mark that one dialog has been created
	hello();

	//-- Center and bring to front
	setCenter( hwnd(), app()->mainhwnd() );
	setFront( hwnd() );

	//-- Icon
	path = m_fname.basedir, path += m_fname.sname;
	hImS = (HIMAGELIST)::SHGetFileInfo( path, 0, &sfi, sizeof(sfi), SHGFI_SYSICONINDEX | SHGFI_ICON | SHGFI_SMALLICON );
	hImL = (HIMAGELIST)::SHGetFileInfo( path, 0, &lfi, sizeof(lfi), SHGFI_SYSICONINDEX | SHGFI_ICON | SHGFI_LARGEICON );
	sendMsg( WM_SETICON, ICON_BIG,   (LPARAM)lfi.hIcon );
	sendMsg( WM_SETICON, ICON_SMALL, (LPARAM)sfi.hIcon );

	//-- Title
	sendMsg( WM_SETTEXT, 0, (LPARAM)kiPath(m_fname.lname).name() );

	//-- Extraction destination (display as long path even if m_ddir is short path)
	{
		char longdir[MAX_PATH];
		if( ::GetLongPathName((const char*)m_ddir, longdir, MAX_PATH) == 0 )
		{
			// GetLongPathName fails when the path ends in a not-yet-existing
			// component (e.g. a subdirectory generated by generate_dirname).
			// Convert the parent directory instead, then re-append the leaf.
			const char* leafPtr = kiPath::name( (const char*)m_ddir );
			char leaf[MAX_PATH];
			::lstrcpy( leaf, leafPtr );
			kiPath parent( m_ddir );
			if( parent.beDirOnly() &&
				::GetLongPathName((const char*)parent, longdir, MAX_PATH) > 0 )
			{
				int len = ::lstrlen(longdir);
				if( len > 0 && longdir[len-1] != '\\' )
					longdir[len++] = '\\', longdir[len] = '\0';
				::lstrcat( longdir, leaf );
			}
			else
			{
				::lstrcpy( longdir, (const char*)m_ddir );
			}
		}
		sendMsgToItem( IDC_DDIR, WM_SETTEXT, 0, (LPARAM)longdir );
	}

	//-- Monospace font for raw archiver output
	{
		LOGFONT lf;
		::GetObject( (HFONT)sendMsg(WM_GETFONT), sizeof(lf), &lf );
		lf.lfPitchAndFamily = FIXED_PITCH | FF_MODERN;
		lf.lfCharSet = DEFAULT_CHARSET;
		const char* fontName = mycnf().getStr( "ArcViewFont", "Consolas" );
		ki_strcpy( lf.lfFaceName, fontName );
		m_hFont = ::CreateFontIndirect( &lf );
	}
	::SendMessage( item(IDC_FILELIST), WM_SETFONT, (WPARAM)m_hFont, TRUE );
	::SendMessage( item(IDC_FILELIST), LVM_SETEXTENDEDLISTVIEWSTYLE, LVS_EX_FULLROWSELECT, LVS_EX_FULLROWSELECT );
	::SendMessage( item(IDC_FILELIST), LVM_SETIMAGELIST, LVSIL_SMALL, (LPARAM)hImS );

	// Store ListView position (pixels) for LayoutPanes
	m_hTree = item( IDC_FOLDERTREE );
	::SendMessage( m_hTree, TVM_SETIMAGELIST, TVSIL_NORMAL, (LPARAM)hImS );
	{
		RECT lr;
		::GetWindowRect( item(IDC_FILELIST), &lr );
		POINT pt = { lr.left, lr.top };
		::ScreenToClient( hwnd(), &pt );
		m_listLeft = pt.x;
		m_listTop  = pt.y;
		{ int s = mycnf().getInt("ArcViewSplit", 0); if(s > 0) m_listLeft = s; }
	}
	m_hHeader = (HWND)sendMsgToItem( IDC_FILELIST, LVM_GETHEADER, 0, 0 );
	if( m_hHeader )
	{
		::SendMessage( m_hHeader, WM_SETFONT, (WPARAM)m_hFont, TRUE );

		// Disable visual styles on the header → classic gray (COLOR_BTNFACE) background
		typedef HRESULT (WINAPI *FnSWT)(HWND, LPCWSTR, LPCWSTR);
		HMODULE hUx = ::LoadLibrary("uxtheme.dll");
		if( hUx )
		{
			FnSWT pfn = (FnSWT)::GetProcAddress(hUx, "SetWindowTheme");
			if( pfn ) pfn(m_hHeader, L"", L"");
			::FreeLibrary(hUx);
		}

		// Subclass to add WM_ERASEBKGND (gray fill) and WM_PAINT (separator line)
		WNDPROC old = (WNDPROC)(LONG_PTR)::GetWindowLongPtr(m_hHeader, GWLP_WNDPROC);
		::SetProp(m_hHeader, "NHdrProc", (HANDLE)old);
		::SetWindowLongPtr(m_hHeader, GWLP_WNDPROC, (LONG_PTR)HeaderSubclassProc);
	}

	//-- List
	if( !m_pArc->list( m_fname, m_files ) || m_files.len()==0 )
	{
		m_bAble = false;
		ctrl.insertColumn( 0, "", 510 );
		ctrl.insertItem( 0, str.loadRsrc(IDS_NOLIST) );
	}
	else
	{
		m_bAble = ( 0 != (m_pArc->ability() & aMeltEach) );

		// First entry is the column header captured from archiver output (isfile=false)
		const char* colHeader = "";
		unsigned int dataStart = 0;
		if( m_files.len() > 0 && !m_files[0].isfile )
		{
			colHeader = m_files[0].rawline;
			dataStart = 1;
		}
		ctrl.insertColumn( 0, "Name", 160 );
		ctrl.insertColumn( 1, colHeader, 640 );

		// Only build the file-index side table here; ListView population is
		// deferred to FilterListByFolder (triggered by the initial tree select).
		for( unsigned int i=dataStart; i!=m_files.len(); i++ )
			if( m_files[i].isfile )
				m_fileIndices.add( i );

		//-- Register drag & drop format
		FORMATETC fmt;
		fmt.cfFormat = CF_HDROP;
		fmt.ptd      = NULL;
		fmt.dwAspect = DVASPECT_CONTENT;
		fmt.lindex   = -1;
		fmt.tymed    = TYMED_HGLOBAL;
		addFormat( fmt );
	}

		if( !m_bAble )
		{
			static const UINT items[] = { IDC_SELECTINV,IDC_REF,IDC_MELTEACH,IDC_SHOW,IDC_DDIR,IDC_DDIRLABEL };
			for( int i=0; i!=sizeof(items)/sizeof(UINT); i++ )
				::EnableWindow( item(items[i]), FALSE );
		}

	//-- Folder tree
	{
		TVINSERTSTRUCT tvis;
		::ZeroMemory( &tvis, sizeof(tvis) );
		tvis.hParent      = TVI_ROOT;
		tvis.hInsertAfter = TVI_FIRST;
		tvis.item.mask    = TVIF_TEXT | TVIF_PARAM;
		// Folder icon from system image list
		SHFILEINFO fsi; ::ZeroMemory( &fsi, sizeof(fsi) );
		::SHGetFileInfo( "folder", FILE_ATTRIBUTE_DIRECTORY, &fsi, sizeof(fsi),
			SHGFI_SYSICONINDEX | SHGFI_SMALLICON | SHGFI_USEFILEATTRIBUTES );
		m_folderIconIdx = fsi.iIcon;

		kiPath rootLabel( m_fname.lname );
		tvis.item.mask    |= TVIF_IMAGE | TVIF_SELECTEDIMAGE;
		tvis.item.pszText  = const_cast<char*>( rootLabel.name() );
		tvis.item.lParam   = (LPARAM)-1;
		tvis.item.iImage         = sfi.iIcon;
		tvis.item.iSelectedImage = sfi.iIcon;
		HTREEITEM hAll = (HTREEITEM)::SendMessage( m_hTree, TVM_INSERTITEM, 0, (LPARAM)&tvis );
		BuildFolderTree( hAll, fsi.iIcon );

		// Initialize m_folderRawlines as parallel to m_folderPaths (all empty).
		for( unsigned int _i = 0; _i < m_folderPaths.len(); _i++ )
			m_folderRawlines.add( kiStr() );

		// Drop standalone directory entries (e.g. 7z "D...." rows) whose name
		// already exists in the synthesized folder tree, to avoid showing the
		// same folder both as a file row and as a folder row.
		{
			unsigned int write = 0;
			for( unsigned int read = 0; read < m_fileIndices.len(); read++ )
			{
				const char* fn = m_files[ m_fileIndices[read] ].inf.szFileName;
				int fnLen = ::lstrlen( fn );
				bool isDirEntry = false;
				char key[MAX_PATH];
				bool found = false;
				unsigned int bisectPos = 0;
				if( fnLen > 0 && (fn[fnLen-1] == '/' || fn[fnLen-1] == '\\') )
				{
					if( fnLen < MAX_PATH )
					{
						::lstrcpy( key, fn );
						bisectPos = folder_bisect( m_folderPaths, m_folderSorted, key, &found );
					}
				}
				else if( fnLen > 0 && fnLen + 1 < MAX_PATH )
				{
					::lstrcpy( key, fn );
					key[fnLen]   = '\\';
					key[fnLen+1] = '\0';
					bisectPos = folder_bisect( m_folderPaths, m_folderSorted, key, &found );
					if( !found )
					{
						key[fnLen] = '/';
						bisectPos = folder_bisect( m_folderPaths, m_folderSorted, key, &found );
					}
				}
				isDirEntry = found;
				if( !isDirEntry )
					m_fileIndices[write++] = m_fileIndices[read];
				else
				{
					// Clear the selected/isfile union so this entry is not
					// passed to the archiver for extraction and is not hit
					// by the ShellExecute loop in the View handler.
					m_files[ m_fileIndices[read] ].selected = false;
					// Capture rawline for the folder row's info column.
					const char* raw = m_files[ m_fileIndices[read] ].rawline;
					if( raw[0] && bisectPos < m_folderSorted.len() )
					{
						unsigned int fi = m_folderSorted[bisectPos];
						if( fi < m_folderRawlines.len() )
							m_folderRawlines[fi] = kiStr( raw );
					}
				}
			}
			m_fileIndices.forcelen( write );
		}

		// Status bar reports the post-filter file count so that directory
		// entries (e.g. 7z "D...." rows) are not double-counted alongside
		// the synthesized folder rows.
		{
			char tmp[255];
			kiStr full_filename = m_fname.basedir + m_fname.lname;
			wsprintf( tmp, kiStr().loadRsrc(IDS_ARCVIEW_MSG),
				m_fileIndices.len(),
				(const char*)m_pArc->arctype_name(full_filename)
			);
			sendMsgToItem( IDC_STATUSBAR, WM_SETTEXT, 0, (LPARAM)tmp );
		}

		// Reserve capacity so listrow pointers stored in LVITEM.lParam stay
		// stable across FilterListByFolder rebuilds.
		m_rows.alloc( m_fileIndices.len() + m_folderPaths.len() + 1 );
		::SendMessage( m_hTree, TVM_EXPAND,     TVE_EXPAND,  (LPARAM)hAll );
		::SendMessage( m_hTree, TVM_SELECTITEM, TVGN_CARET,  (LPARAM)hAll );
		// Explicit initial population (TVN_SELCHANGED during init may not
		// be forwarded to this dialog's proc).
		if( m_bAble ) FilterListByFolder( -1 );
	}

	//-- Restore saved window size
	{ int w = mycnf().getInt("ArcViewW", 0), h = mycnf().getInt("ArcViewH", 0);
	  if( w > 100 && h > 100 )
	      ::SetWindowPos(hwnd(), NULL, 0, 0, w, h, SWP_NOMOVE|SWP_NOZORDER|SWP_NOACTIVATE); }

	{
		RECT rc, self, ref, child, sbar;
		::GetClientRect( hwnd(), &rc );
		::GetWindowRect( hwnd(), &self );
		::GetWindowRect( item(IDC_REF), &ref );
		::GetWindowRect( item(IDC_FILELIST), &child );
		::GetClientRect( item(IDC_STATUSBAR), &sbar );
		LayoutTopRow( rc.right );
		LayoutPanes( rc.right,
			(self.bottom-ref.bottom)-(child.top-ref.bottom)
			-(sbar.bottom-sbar.top)-10 );
		::SetWindowPos( item(IDC_STATUSBAR), NULL, sbar.left,
			rc.bottom - (sbar.bottom-sbar.top),
			0, 0, SWP_NOSIZE|SWP_NOOWNERZORDER|SWP_NOZORDER );
	}

	return FALSE;
}

bool CArcViewDlg::onOK()
{
	setdir();
	m_pArc->melt( m_fname, m_ddir );
	myapp().open_folder( m_ddir, 1 );
	kiSUtil::switchCurDirToExeDir(); // Just to be safe
	return onCancel();
}

bool CArcViewDlg::onCancel()
{
	//-- Save window size and splitter position
	{ RECT wr; ::GetWindowRect(hwnd(), &wr);
	  mycnf().putInt("ArcViewW",     wr.right  - wr.left);
	  mycnf().putInt("ArcViewH",     wr.bottom - wr.top);
	  mycnf().putInt("ArcViewSplit", m_listLeft); }

	::SetCurrentDirectory( m_fname.basedir );
	m_tdir.remove();
	if( kiSUtil::exist(m_tdir) )
	{
		kiStr tmp(600);
		if( IDNO==app()->msgBox( tmp.loadRsrc(IDS_EXECUTING), NULL, MB_YESNO|MB_DEFBUTTON2 ) )
			return false;
	}

	kiListView(this,IDC_FILELIST).setImageList( NULL, NULL );
	if( m_hHeader )
	{
		WNDPROC old = (WNDPROC)::GetProp(m_hHeader, "NHdrProc");
		if( old ) ::SetWindowLongPtr(m_hHeader, GWLP_WNDPROC, (LONG_PTR)old);
		::RemoveProp(m_hHeader, "NHdrProc");
		m_hHeader = NULL;
	}
	if( m_hFont ) { ::DeleteObject(m_hFont); m_hFont=NULL; }
	byebye();
	return true;
}

bool CArcViewDlg::giveData( const FORMATETC& fmt, STGMEDIUM* stg, bool firstcall )
{
	if( firstcall )
		if( 0x8000<=m_pArc->melt( m_fname, m_tdir, &m_files ) )
			return false;

	unsigned int i;
	BOOL fWide = (app()->osver().dwPlatformId==VER_PLATFORM_WIN32_NT);
	kiArray<kiPath> lst;
	kiPath tmp;
	int flen = 0;
	wchar_t wbuf[600];

	for( i=0; i!=m_files.len(); i++ )
		if( m_files[i].selected )
		{
			tmp = m_tdir;
			tmp += m_files[i].inf.szFileName;

			lst.add( tmp );
			if( fWide )
				flen += (::MultiByteToWideChar( CP_ACP, 0, tmp, -1, wbuf, 600 )+1)*2;
			else
				flen += (tmp.len()+1);
		}

	HDROP hDrop = (HDROP)::GlobalAlloc( GHND, sizeof(DROPFILES)+flen+1 );

	DROPFILES* dr = (DROPFILES*)::GlobalLock( hDrop );
	dr->pFiles = sizeof(DROPFILES);
	dr->pt.x   = dr->pt.y = 0;
	dr->fNC    = FALSE;
	dr->fWide  = fWide;

	char* buf = (char*)(&dr[1]);
	for( i=0; i!=lst.len(); i++ )
	{
		if( fWide )
		{
			flen = ::MultiByteToWideChar( CP_ACP, 0, lst[i], -1, wbuf, 600 );
			ki_memcpy( buf, wbuf, flen*2 );
			for( int k=0; k!=flen; k++ )
				if( ((wchar_t*)buf)[k] == '/' )
					((wchar_t*)buf)[k] = '\\';
			buf += flen*2;
		}
		else
		{
			ki_strcpy( buf,lst[i] );
			kiStr::replaceToBackslash( buf );
			buf += lst[i].len() + 1;
		}
	}
	*buf=0;
	if( fWide )
		buf[1]='\0';

	::GlobalUnlock( hDrop );

	stg->hGlobal        = hDrop;
	stg->tymed          = TYMED_HGLOBAL;
	stg->pUnkForRelease = NULL;
	return true;
}

BOOL CALLBACK CArcViewDlg::proc( UINT msg, WPARAM wp, LPARAM lp )
{
	switch( msg )
	{
	//-- Specify main window ---------------------
	case WM_ACTIVATE:
		if( LOWORD(wp)==WA_ACTIVE || LOWORD(wp)==WA_CLICKACTIVE )
		{
			app()->setMainWnd( this );
			return TRUE;
		}
		break;

	//-- Resize-related processing ---------------------
	case WM_GETMINMAXINFO:
		{
			RECT self,child,client;
			::GetWindowRect( hwnd(), &self );
			::GetWindowRect( item(IDC_REF), &child );
			::GetClientRect( hwnd(), &client );
			RECT label,ok,melt,show,inv,ref;
			::GetWindowRect( item(IDC_DDIRLABEL), &label );
			::GetWindowRect( item(IDOK), &ok );
			::GetWindowRect( item(IDC_MELTEACH), &melt );
			::GetWindowRect( item(IDC_SHOW), &show );
			::GetWindowRect( item(IDC_SELECTINV), &inv );
			::GetWindowRect( item(IDC_REF), &ref );
			POINT& sz = ((MINMAXINFO*)lp)->ptMinTrackSize;
			const int minEdit = 220;
			const int margin = 7, gap = 3, groupGap = 7;
			int minClientW = margin + (label.right-label.left) + gap
				+ minEdit + gap + (ref.right-ref.left) + groupGap
				+ (ok.right-ok.left) + gap + (melt.right-melt.left)
				+ gap + (show.right-show.left) + gap + (inv.right-inv.left) + margin;
			sz.x = minClientW + ((self.right-self.left) - (client.right-client.left));
			sz.y = child.bottom - self.top + 100;
		}
		return TRUE;
	case WM_SIZE:
		if( wp!=SIZE_MAXHIDE && wp!=SIZE_MINIMIZED )
		{
			RECT self,ref,child,sbar;
			::GetWindowRect( hwnd(), &self );
			::GetWindowRect( item(IDC_REF), &ref );
			::GetWindowRect( item(IDC_FILELIST), &child );
			::GetClientRect( item(IDC_STATUSBAR), &sbar );

			int newH = (self.bottom-ref.bottom)-(child.top-ref.bottom)
				   -(sbar.bottom-sbar.top)-10;
			LayoutTopRow( (int)(short)LOWORD(lp) );
			LayoutPanes( (int)(short)LOWORD(lp), newH );

			::GetClientRect( hwnd(), &self );
			::SetWindowPos( item(IDC_STATUSBAR), NULL, sbar.left,
				self.bottom - (sbar.bottom-sbar.top),
				0, 0, SWP_NOSIZE|SWP_NOOWNERZORDER|SWP_NOZORDER );
		}
		break;

	case WM_SETCURSOR:
		if( LOWORD(lp)==HTCLIENT )
		{
			POINT pt; ::GetCursorPos(&pt); ::ScreenToClient(hwnd(),&pt);
			if( pt.x >= m_listLeft-ARCVIEW_SPLITTER_WIDTH && pt.x < m_listLeft )
			{
				::SetCursor( ::LoadCursor(NULL, IDC_SIZEWE) );
				return TRUE;
			}
		}
		break;

	case WM_LBUTTONDOWN:
		{
			int x = (int)(short)LOWORD(lp);
			if( x >= m_listLeft-ARCVIEW_SPLITTER_WIDTH && x < m_listLeft )
			{
				m_bDragging    = true;
				m_dragX        = x;
				m_dragListLeft = m_listLeft;
				::SetCapture( hwnd() );
				::SetCursor( ::LoadCursor(NULL, IDC_SIZEWE) );
				return TRUE;
			}
		}
		break;

	case WM_MOUSEMOVE:
		if( m_bDragging )
		{
			DrawSplitterGhost( m_ghostX );  // erase old
			int newLeft = m_dragListLeft + (int)(short)LOWORD(lp) - m_dragX;
			RECT rc; ::GetClientRect( hwnd(), &rc );
			const int SP=ARCVIEW_SPLITTER_WIDTH, minTree=30, minList=80;
			if( newLeft < minTree+SP )      newLeft = minTree+SP;
			if( newLeft > rc.right-minList ) newLeft = rc.right-minList;
			m_listLeft = newLeft;
			m_ghostX   = newLeft - SP/2;  // center of splitter strip
			DrawSplitterGhost( m_ghostX );  // draw at new position
		}
		break;

	case WM_LBUTTONUP:
		if( m_bDragging )
		{
			DrawSplitterGhost( m_ghostX );  // erase ghost
			m_ghostX    = -1;
			m_bDragging = false;
			::ReleaseCapture();
			RECT rc, lr;
			::GetClientRect( hwnd(), &rc );
			::GetWindowRect( item(IDC_FILELIST), &lr );
			int dlgW  = rc.right;
			int paneH = lr.bottom - lr.top;
			LayoutPanes( dlgW, paneH );
			::RedrawWindow( hwnd(), NULL, NULL,
				RDW_INVALIDATE | RDW_UPDATENOW | RDW_ALLCHILDREN );
		}
		break;

	case WM_CAPTURECHANGED:
		if( m_bDragging )
		{
			DrawSplitterGhost( m_ghostX );
			m_ghostX    = -1;
			m_bDragging = false;
		}
		break;

	case WM_NOTIFY:
		if( wp==IDC_FOLDERTREE )
		{
			NMTREEVIEW* ptv = (NMTREEVIEW*)lp;
			if( ptv->hdr.code == TVN_SELCHANGED )
			{
				FilterListByFolder( (int)ptv->itemNew.lParam );
				return TRUE;
			}
		}
		if( wp==IDC_FILELIST && m_bAble )
		{
			NMHDR* phdr=(NMHDR*)lp;
			if( phdr->code==LVN_BEGINDRAG || phdr->code==LVN_BEGINRDRAG )
			{
				clearSelections();
				if( setSelection() )
					kiDropSource::DnD( this, DROPEFFECT_COPY );
				return TRUE;
			}
			else if( phdr->code==NM_DBLCLK )
			{
				NMITEMACTIVATE* pia = (NMITEMACTIVATE*)lp;
				if( pia->iItem >= 0 )
				{
					LVITEM it;
					it.mask = LVIF_PARAM;
					it.iItem = pia->iItem;
					it.iSubItem = 0;
					if( sendMsgToItem( IDC_FILELIST, LVM_GETITEM, 0, (LPARAM)&it ) )
					{
						listrow* r = (listrow*)it.lParam;
						if( r && r->isFolder )
						{
							HTREEITEM hTarget = NULL;
							if( r->idx < 0 )
								hTarget = (HTREEITEM)::SendMessage( m_hTree, TVM_GETNEXTITEM, TVGN_ROOT, 0 );
							else if( (unsigned int)r->idx < m_treeNodes.len() )
								hTarget = m_treeNodes[r->idx];
							if( hTarget )
								::SendMessage( m_hTree, TVM_SELECTITEM, TVGN_CARET, (LPARAM)hTarget );
							return TRUE;
						}
					}
				}
				sendMsg( WM_COMMAND, IDC_SHOW );
			}
			else if( phdr->code==NM_RCLICK )
			{
				clearSelections();
				if( setSelection() )
					DoRMenu();
			}
		}
		break;

	case WM_COMMAND:
		switch( LOWORD(wp) )
		{
		case IDC_SELECTINV: // Invert selection
			{
				LVITEM item;
				item.mask = LVIF_STATE;
				item.stateMask = LVIS_SELECTED;
				int j,m = static_cast<int>(sendMsgToItem( IDC_FILELIST, LVM_GETITEMCOUNT ));
				for( j=0; j!=m; j++ )
				{
					item.state = ~static_cast<UINT>(sendMsgToItem( IDC_FILELIST, LVM_GETITEMSTATE, j, LVIS_SELECTED ));
					sendMsgToItem( IDC_FILELIST, LVM_SETITEMSTATE, j, (LPARAM)&item );
				}
				::SetFocus( this->item(IDC_FILELIST) );
			}
			return TRUE;

		case IDC_REF: // Set extraction destination
			kiSUtil::getFolderDlgOfEditBox( item(IDC_DDIR), hwnd(), kiStr().loadRsrc(IDS_CHOOSEDIR) );
			return TRUE;

		case IDC_MELTEACH: // Partial extraction
			clearSelections();
			if( setSelection() )
			{
				setdir();
				int result = m_pArc->melt( m_fname, m_ddir, &m_files );
				if( result<0x8000 )
					myapp().open_folder( m_ddir, 1 );
				else if( result != 0x8020 )
				{
					char str[255];
					wsprintf( str, "%s\nError No: [%x]",
						(const char*)kiStr().loadRsrc( IDS_M_ERROR ), result );
					app()->msgBox( str );
				}
				kiSUtil::switchCurDirToExeDir(); // Just to be safe
			}
			return TRUE;

		case IDC_SHOW: // Show
			{
				// If a folder row is selected, navigate into it instead of viewing.
				LVITEM it;
				it.mask = LVIF_PARAM | LVIF_STATE;
				it.iSubItem = 0;
				it.stateMask = LVIS_SELECTED;
				bool folderFound = false;
				int folderTreeIdx = -1;
				for( it.iItem = 0;
				     sendMsgToItem( IDC_FILELIST, LVM_GETITEM, 0, (LPARAM)&it );
				     it.iItem++ )
				{
					if( 0 == (LVIS_SELECTED & it.state) ) continue;
					listrow* r = (listrow*)it.lParam;
					if( r && r->isFolder )
					{ folderFound = true; folderTreeIdx = r->idx; break; }
				}
				if( folderFound )
				{
					HTREEITEM hTarget = NULL;
					if( folderTreeIdx < 0 )
						hTarget = (HTREEITEM)::SendMessage( m_hTree, TVM_GETNEXTITEM, TVGN_ROOT, 0 );
					else if( (unsigned int)folderTreeIdx < m_treeNodes.len() )
						hTarget = m_treeNodes[folderTreeIdx];
					if( hTarget )
						::SendMessage( m_hTree, TVM_SELECTITEM, TVGN_CARET, (LPARAM)hTarget );
					return TRUE;
				}
			}
			clearSelections();
			if( setSelection() )
			{
				int assocCnt = hlp_cnt_check();
				if( 0x8000 > m_pArc->melt( m_fname, m_tdir, &m_files ) )
				{
					if( assocCnt != -1 )
						m_files[assocCnt].selected = false;
					for( unsigned i=0; i!=m_files.len(); i++ )
						if( m_files[i].selected )
						{
							kiPath tmp(m_tdir);
							char yen[MAX_PATH];
							ki_strcpy( yen, m_files[i].inf.szFileName );
							kiStr::replaceToBackslash( yen );
							tmp += yen;
							::ShellExecute( hwnd(), NULL, tmp, NULL, m_tdir, SW_SHOWDEFAULT );
						}
				}
				kiSUtil::switchCurDirToExeDir(); // Just to be safe
			}
			return TRUE;
		}
	}
	return FALSE;
}

bool CArcViewDlg::setSelection()
{
	bool x = false;
	LVITEM it;
	it.mask = LVIF_PARAM | LVIF_STATE;
	it.iSubItem = 0;
	it.stateMask = LVIS_SELECTED;
	for( it.iItem = 0;
	     sendMsgToItem( IDC_FILELIST, LVM_GETITEM, 0, (LPARAM)&it );
	     it.iItem++ )
	{
		if( 0 == (LVIS_SELECTED & it.state) ) continue;
		listrow* r = (listrow*)it.lParam;
		if( !r ) continue;
		if( r->isFolder )
		{
			// Recursively select every file under this folder path.
			if( r->idx < 0 || (unsigned int)r->idx >= m_folderPaths.len() ) continue;
			const char* pfx = m_folderPaths[ r->idx ];
			int pfxLen = ::lstrlen( pfx );
			for( unsigned int fi = 0; fi < m_fileIndices.len(); fi++ )
			{
				arcfile& af = m_files[ m_fileIndices[fi] ];
				if( (int)::lstrlen(af.inf.szFileName) >= pfxLen
				 && ki_memcmp(af.inf.szFileName, pfx, pfxLen) )
				{
					af.selected = true;
					x = true;
				}
			}
		}
		else
		{
			if( r->idx < 0 || (unsigned int)r->idx >= m_fileIndices.len() ) continue;
			m_files[ m_fileIndices[ r->idx ] ].selected = true;
			x = true;
		}
	}
	return x;
}

int CArcViewDlg::hlp_cnt_check()
{
	// Whether the first selected file is .hlp
	unsigned int i=0;
	for( ; i!=m_files.len(); i++ )
		if( m_files[i].selected )
			break;
	if( i==m_files.len() )
		return -1;
	ptrdiff_t x = kiPath::ext(m_files[i].inf.szFileName)-m_files[i].inf.szFileName;
	if( 0!=ki_strcmpi( "hlp", m_files[i].inf.szFileName+x ) )
		return -1;

	// .cnt filename
	char cntpath[FNAME_MAX32];
	ki_strcpy( cntpath, m_files[i].inf.szFileName );
	cntpath[x]='c', cntpath[x+1]='n', cntpath[x+2]='t';

	// Also temporarily select .cnt
	for( i=0; i!=m_files.len(); i++ )
		if( 0==ki_strcmpi( cntpath, m_files[i].inf.szFileName ) )
		{
			if( m_files[i].selected )
				return -1;
			m_files[i].selected = true;
			return i;
		}
	return -1;
}

void CArcViewDlg::GenerateDirMenu( HMENU m, int& id, StrArray* sx, const kiPath& pth )
{
	// List folder contents
	kiFindFile ff;
	ff.begin( kiPath(pth)+="*" );
	for( WIN32_FIND_DATA fd; ff.next(&fd); )
		if( fd.cFileName[0]!='.'
		 && !(fd.dwFileAttributes & FILE_ATTRIBUTE_HIDDEN) )
		{
			kiPath fullpath(pth); fullpath+=fd.cFileName;
			const int pID=id;
			MENUITEMINFO mi = { sizeof(MENUITEMINFO) };

			if( fd.dwFileAttributes & FILE_ATTRIBUTE_DIRECTORY )
			{
				// Recursively
				mi.fMask = MIIM_SUBMENU | 0x00000040;// (MIIM_STRING)
				mi.hSubMenu = ::CreatePopupMenu();
				GenerateDirMenu( mi.hSubMenu, id, sx,
					kiPath(kiPath(fullpath)+="\\") );
			}
			else
			{
				const char* ext = kiPath::ext(fd.cFileName);
				if( ::lstrlen(ext) > 4 ) continue;
				if( 0==::lstrcmpi(ext,"lnk") )
					*const_cast<char*>(ext-1) = '\0';
				mi.fMask = MIIM_ID | 0x00000040;// (MIIM_STRING)
				mi.wID = id++;
				sx->add( fullpath );
			}

			mi.dwTypeData = const_cast<char*>((const char*)fd.cFileName);
			mi.cch        = ::lstrlen(fd.cFileName);
			::InsertMenuItem( m, pID, FALSE, &mi );
		}
}

void CArcViewDlg::LayoutTopRow( int dlgW )
{
	const int margin   = 7;
	const int gap      = 3;
	const int labelGap = 1;
	const int groupGap = 7;

	RECT rcLabel, rcEdit, rcRef, rcOK, rcMelt, rcShow, rcInv;
	::GetWindowRect( item(IDC_DDIRLABEL), &rcLabel );
	::GetWindowRect( item(IDC_DDIR),      &rcEdit );
	::GetWindowRect( item(IDC_REF),       &rcRef );
	::GetWindowRect( item(IDOK),          &rcOK );
	::GetWindowRect( item(IDC_MELTEACH),  &rcMelt );
	::GetWindowRect( item(IDC_SHOW),      &rcShow );
	::GetWindowRect( item(IDC_SELECTINV), &rcInv );

	const int labelW = rcLabel.right - rcLabel.left;
	const int labelH = rcLabel.bottom - rcLabel.top;
	const int editH = rcEdit.bottom - rcEdit.top;
	const int refW  = rcRef.right - rcRef.left;
	const int refH  = rcRef.bottom - rcRef.top;
	const int okW   = rcOK.right - rcOK.left;
	const int okH   = rcOK.bottom - rcOK.top;
	const int meltW = rcMelt.right - rcMelt.left;
	const int meltH = rcMelt.bottom - rcMelt.top;
	const int showW = rcShow.right - rcShow.left;
	const int showH = rcShow.bottom - rcShow.top;
	const int invW  = rcInv.right - rcInv.left;
	const int invH  = rcInv.bottom - rcInv.top;
	int topBandH = m_listTop;
	if( topBandH <= 0 ) topBandH = 20;
	const int shiftY = 2;
	const int labelY = (topBandH - labelH) / 2 + shiftY;
	const int editY  = (topBandH - editH ) / 2 + shiftY;
	const int refY   = (topBandH - refH  ) / 2 + shiftY;
	const int okY    = (topBandH - okH   ) / 2 + shiftY;
	const int meltY  = (topBandH - meltH ) / 2 + shiftY;
	const int showY  = (topBandH - showH ) / 2 + shiftY;
	const int invY   = (topBandH - invH  ) / 2 + shiftY;

	int x = dlgW - margin;
	const int invX  = x - invW;  x = invX  - gap;
	const int showX = x - showW; x = showX - gap;
	const int meltX = x - meltW; x = meltX - gap;
	const int okX   = x - okW;
	const int editX = margin + labelW + labelGap;
	const int editW = okX - groupGap - editX - gap - refW;
	const int browseX = editX + editW + gap;

	HDWP hdwp = ::BeginDeferWindowPos( 7 );
	if( hdwp )
		hdwp = ::DeferWindowPos( hdwp, item(IDC_DDIRLABEL), NULL,
			margin, labelY, labelW, labelH, SWP_NOOWNERZORDER|SWP_NOZORDER );
	if( hdwp )
		hdwp = ::DeferWindowPos( hdwp, item(IDC_DDIR), NULL,
			editX, editY, editW, editH, SWP_NOOWNERZORDER|SWP_NOZORDER );
	if( hdwp )
		hdwp = ::DeferWindowPos( hdwp, item(IDC_REF), NULL,
			browseX, refY, refW, refH, SWP_NOOWNERZORDER|SWP_NOZORDER );
	if( hdwp )
		hdwp = ::DeferWindowPos( hdwp, item(IDOK), NULL,
			okX, okY, okW, okH, SWP_NOOWNERZORDER|SWP_NOZORDER );
	if( hdwp )
		hdwp = ::DeferWindowPos( hdwp, item(IDC_MELTEACH), NULL,
			meltX, meltY, meltW, meltH, SWP_NOOWNERZORDER|SWP_NOZORDER );
	if( hdwp )
		hdwp = ::DeferWindowPos( hdwp, item(IDC_SHOW), NULL,
			showX, showY, showW, showH, SWP_NOOWNERZORDER|SWP_NOZORDER );
	if( hdwp )
		hdwp = ::DeferWindowPos( hdwp, item(IDC_SELECTINV), NULL,
			invX, invY, invW, invH, SWP_NOOWNERZORDER|SWP_NOZORDER );
	if( hdwp )
		::EndDeferWindowPos( hdwp );
}

void CArcViewDlg::DrawSplitterGhost( int x )
{
	if( x < 0 ) return;
	RECT cr; ::GetClientRect( hwnd(), &cr );
	RECT sr; ::GetClientRect( item(IDC_STATUSBAR), &sr );
	int lineH = cr.bottom - m_listTop - (sr.bottom - sr.top);
	HDC hdc = ::GetDC( hwnd() );
	HBRUSH old = (HBRUSH)::SelectObject( hdc, ::GetStockObject(GRAY_BRUSH) );
	::PatBlt( hdc, x, m_listTop, 1, lineH, PATINVERT );
	::SelectObject( hdc, old );
	::ReleaseDC( hwnd(), hdc );
}

void CArcViewDlg::LayoutPanes( int dlgW, int paneH )
{
	const int SP = ARCVIEW_SPLITTER_WIDTH; // splitter strip width (pixels, dialog client area)
	const int minTree = 30;
	const int minList = 80;
	if( m_listLeft < minTree + SP ) m_listLeft = minTree + SP;
	if( m_listLeft > dlgW - minList ) m_listLeft = dlgW - minList;

	// Update both controls atomically to avoid flicker
	HDWP hdwp = ::BeginDeferWindowPos(2);
	if( hdwp && m_hTree )
		hdwp = ::DeferWindowPos( hdwp, m_hTree, NULL,
			0, m_listTop, m_listLeft - SP, paneH,
			SWP_NOOWNERZORDER|SWP_NOZORDER );
	if( hdwp )
		hdwp = ::DeferWindowPos( hdwp, item(IDC_FILELIST), NULL,
			m_listLeft, m_listTop, dlgW - m_listLeft, paneH,
			SWP_NOOWNERZORDER|SWP_NOZORDER );
	if( hdwp )
		::EndDeferWindowPos( hdwp );

	// Repaint splitter strip only
	RECT sr = { m_listLeft - SP, m_listTop, m_listLeft, m_listTop + paneH };
	::InvalidateRect( hwnd(), &sr, TRUE );
}

// Binary search in m_folderSorted for the path buf.
// Returns the index in m_folderSorted where buf is (or should be inserted).
// Sets *found = true if an exact match exists.
static unsigned int folder_bisect( const StrArray& paths, const kiArray<unsigned int>& sorted,
	const char* buf, bool* found )
{
	unsigned int lo = 0, hi = sorted.len();
	while( lo < hi )
	{
		unsigned int mid = (lo + hi) / 2;
		int cmp = ::lstrcmp( paths[ sorted[mid] ], buf );
		if( cmp == 0 ) { *found = true; return mid; }
		if( cmp < 0 )  lo = mid + 1;
		else           hi = mid;
	}
	*found = false;
	return lo;
}

void CArcViewDlg::BuildFolderTree( HTREEITEM hRoot, int folderIconIdx )
{
	for( unsigned int fi=0; fi!=m_fileIndices.len(); fi++ )
	{
		const char* fn = m_files[ m_fileIndices[fi] ].inf.szFileName;
		for( const char* p=fn; *p; p++ )
		{
			if( *p != '/' && *p != '\\' ) continue;

			int len = (int)(p - fn) + 1;
			char buf[MAX_PATH];
			if( len >= MAX_PATH ) continue;
			::CopyMemory( buf, fn, len );
			buf[len] = '\0';

			// Skip if already registered (binary search)
			bool found;
			unsigned int pos = folder_bisect( m_folderPaths, m_folderSorted, buf, &found );
			if( found ) continue;

			// Find parent node (strip last component from buf, then binary search)
			HTREEITEM hParent = hRoot;
			for( int k=len-2; k>=0; k-- )
			{
				if( buf[k] == '/' || buf[k] == '\\' )
				{
					char pbuf[MAX_PATH];
					::CopyMemory( pbuf, buf, k+1 );
					pbuf[k+1] = '\0';
					bool pfound;
					unsigned int ppos = folder_bisect( m_folderPaths, m_folderSorted, pbuf, &pfound );
					if( pfound )
						hParent = m_treeNodes[ m_folderSorted[ppos] ];
					break;
				}
			}

			// Node label: last path component (excluding trailing separator)
			int labelStart = 0;
			for( int k=len-2; k>=0; k-- )
				if( buf[k] == '/' || buf[k] == '\\' ) { labelStart = k+1; break; }
			char label[MAX_PATH];
			int labelLen = len - 1 - labelStart;
			::CopyMemory( label, buf+labelStart, labelLen );
			label[labelLen] = '\0';

			TVINSERTSTRUCT tvis;
			::ZeroMemory( &tvis, sizeof(tvis) );
			tvis.hParent      = hParent;
			tvis.hInsertAfter = TVI_SORT;
			tvis.item.mask    = TVIF_TEXT | TVIF_PARAM | TVIF_IMAGE | TVIF_SELECTEDIMAGE;
			tvis.item.pszText = label;
			tvis.item.lParam  = (LPARAM)m_folderPaths.len();
			tvis.item.iImage         = folderIconIdx;
			tvis.item.iSelectedImage = folderIconIdx;
			HTREEITEM h = (HTREEITEM)::SendMessage( m_hTree, TVM_INSERTITEM, 0, (LPARAM)&tvis );

			// Register: append to paths/nodes, insert index into sorted list
			unsigned int newIdx = m_folderPaths.len();
			m_folderPaths.add( kiStr(buf) );
			m_treeNodes.add( h );
			m_folderSorted.add( 0 );  // extend by 1 (value overwritten below)
			for( unsigned int k=newIdx; k>pos; k-- )
				m_folderSorted[k] = m_folderSorted[k-1];
			m_folderSorted[pos] = newIdx;
		}
	}
}

void CArcViewDlg::FilterListByFolder( int folderIdx )
{
	// Clear selection on all file entries before rebuilding the list
	clearSelections();

	kiListView ctrl( this, IDC_FILELIST );
	::SendMessage( item(IDC_FILELIST), WM_SETREDRAW, FALSE, 0 );
	::SendMessage( item(IDC_FILELIST), LVM_DELETEALLITEMS, 0, 0 );
	m_rows.empty();

	const char* prefix    = NULL;
	int         prefixLen = 0;
	if( folderIdx >= 0 && (unsigned int)folderIdx < m_folderPaths.len() )
	{
		prefix    = m_folderPaths[folderIdx];
		prefixLen = ::lstrlen( prefix );
	}

	// Collect immediate child folders of the current prefix. A path in
	// m_folderPaths ends in a separator, so a direct child has exactly one
	// separator (at the end) after stripping the prefix.
	kiArray<unsigned int> childFolders;
	for( unsigned int j=0; j<m_folderPaths.len(); j++ )
	{
		const char* path = m_folderPaths[j];
		int pathLen = ::lstrlen( path );
		const char* tail; int tailLen;
		if( prefix )
		{
			if( pathLen <= prefixLen ) continue;
			if( !ki_memcmp(path, prefix, prefixLen) ) continue;
			tail = path + prefixLen;
			tailLen = pathLen - prefixLen;
		}
		else
		{
			tail = path;
			tailLen = pathLen;
		}
		int sepCount = 0, lastSepPos = -1;
		for( int k=0; k<tailLen; k++ )
			if( tail[k]=='/' || tail[k]=='\\' )
			{ sepCount++; lastSepPos = k; }
		if( sepCount != 1 || lastSepPos != tailLen - 1 ) continue;
		childFolders.add( j );
	}

	// Sort child folders by leaf name (case-insensitive).
	for( unsigned int a=1; a<childFolders.len(); a++ )
	{
		unsigned int key = childFolders[a];
		char keyLeaf[MAX_PATH];
		extract_folder_leaf( m_folderPaths[key], keyLeaf );
		int b = (int)a - 1;
		while( b >= 0 )
		{
			char otherLeaf[MAX_PATH];
			extract_folder_leaf( m_folderPaths[childFolders[b]], otherLeaf );
			if( ::lstrcmpi(otherLeaf, keyLeaf) <= 0 ) break;
			childFolders[b+1] = childFolders[b];
			b--;
		}
		childFolders[b+1] = key;
	}

	unsigned int k = 0;

	// Insert ".." entry when browsing a subfolder.
	if( prefix )
	{
		int parentIdx = -1;
		{
			int end = prefixLen - 1;
			while( end > 0 && prefix[end-1] != '/' && prefix[end-1] != '\\' )
				end--;
			if( end > 0 && end < MAX_PATH )
			{
				char pbuf[MAX_PATH];
				::CopyMemory( pbuf, prefix, end );
				pbuf[end] = '\0';
				bool pfound;
				unsigned int ppos = folder_bisect( m_folderPaths, m_folderSorted, pbuf, &pfound );
				if( pfound )
					parentIdx = (int)m_folderSorted[ppos];
			}
		}
		listrow lr; lr.isFolder = true; lr.idx = parentIdx;
		m_rows.add( lr );
		ctrl.insertItem( k, "..", (LPARAM)&m_rows[m_rows.len()-1], m_folderIconIdx );
		k++;
	}

	// Insert folder rows first.
	for( unsigned int a=0; a<childFolders.len(); a++ )
	{
		unsigned int fp = childFolders[a];
		char leaf[MAX_PATH];
		extract_folder_leaf( m_folderPaths[fp], leaf );
		listrow lr; lr.isFolder = true; lr.idx = (int)fp;
		m_rows.add( lr );
		ctrl.insertItem( k, leaf, (LPARAM)&m_rows[m_rows.len()-1], m_folderIconIdx );
		if( fp < m_folderRawlines.len() && ((const char*)m_folderRawlines[fp])[0] )
			ctrl.setSubItem( k, 1, (const char*)m_folderRawlines[fp] );
		k++;
	}

	// Then insert files directly in the selected folder.
	for( unsigned int fi=0; fi<m_fileIndices.len(); fi++ )
	{
		arcfile& af = m_files[ m_fileIndices[fi] ];
		const char* fn = af.inf.szFileName;
		const char* lastSep = NULL;
		for( const char* p=fn; *p; p++ )
			if( *p=='/' || *p=='\\' ) lastSep = p;
		int dirLen = lastSep ? (int)(lastSep - fn) + 1 : 0;
		if( prefix )
		{
			if( dirLen != prefixLen || !ki_memcmp(fn, prefix, prefixLen) )
				continue;
		}
		else
		{
			if( dirLen != 0 )
				continue;
		}
		listrow lr; lr.isFolder = false; lr.idx = (int)fi;
		m_rows.add( lr );
		ctrl.insertItem( k, kiPath::name(af.inf.szFileName),
			(LPARAM)&m_rows[m_rows.len()-1], cachedIconFor(af.inf.szFileName) );
		ctrl.setSubItem( k, 1, af.rawline );
		k++;
	}
	::SendMessage( item(IDC_FILELIST), WM_SETREDRAW, TRUE, 0 );
	::InvalidateRect( item(IDC_FILELIST), NULL, TRUE );
}

void CArcViewDlg::DoRMenu()
{
	// Create menu
	HMENU m = ::CreatePopupMenu();
	POINT pt; ::GetCursorPos( &pt );
	const int IDSTART = 128;

	// List folder contents and add to menu
	int id = IDSTART;
	StrArray lst;
	GenerateDirMenu( m, id, &lst, kiPath(CSIDL_SENDTO) );

	// Show menu
	id = ::TrackPopupMenu( m,
		TPM_LEFTALIGN|TPM_TOPALIGN|TPM_RETURNCMD|TPM_NONOTIFY,
		pt.x, pt.y, 0, hwnd(), NULL );
	::DestroyMenu( m );

	// Result processing
	if( id != 0 )
	{
		kiStr cmd;
		if( 0x8000>m_pArc->melt( m_fname, m_tdir, &m_files ) )
		{
			for( UINT i=0; i!=m_files.len(); i++ )
				if( m_files[i].selected )
				{
					cmd += "\"";
					cmd += m_tdir;
					const char* buf = m_files[i].inf.szFileName;
					for( int k=0; buf[k]; ++k )
						cmd += ( buf[k]=='/' ? '\\' : buf[k] );
					cmd += "\" ";
				}
			ShellExecute(hwnd(),NULL,lst[id-IDSTART],cmd,NULL,SW_SHOW);
		}
	}
}
